### PR TITLE
Use Rack::BodyProxy instead of custom Body class

### PR DESCRIPTION
**Pull request by rymai**
This solves a strange issue where a X-Sendfile header wouldn't be set correctly.

References:

- http://www.rubydoc.info/github/rack/rack/Rack/BodyProxy

### CODE REVIEW

**Comment by rymai** [comment]
@jnunemaker Any chance to get this merged? :)

**Comment by jnunemaker** [comment]
@rymai I don't believe I'm a maintainer of this repo. Looks like a solid change to me though if that helps whoever is maintaining this.

**Comment by rymai** [comment]
@jnunemaker Oops, sorry you were the first one in the autocomplete... 🤦‍♂️ I should have pinged @dewski! :)

**Comment by dewski** [comment]
peek-performance_bar 1.3.0 has been published to RubyGems. Thanks for your contribution!

**Comment by rymai** [comment]
@dewski Awesome, thank you!

**Pull request merged**
